---

- name: install mariadb
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - mariadb-server
    - python-pymysql

- name: create mariadb configuration file
  template: src=mysqld_openstack.cnf dest=/etc/mysql/conf.d/mysqld_openstack.cnf

- name: restart mariadb
  service: name=mysql state=restarted

- name: Install the Python MySQLDB module
  apt: name=python-mysqldb

- name: create database
  mysql_db:
    name: "{{ item }}"
  with_items: "{{ mariadb_databases }}"

- name: create cinder user
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: present
  with_items: "{{ mariadb_users }}"

# TODO:mysql_secure_installation
