VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false

  config.vm.define "controller" do |cont|
    cont.vm.box = "ubuntu/trusty64"
    cont.vm.hostname = "controller"
    cont.vm.network "private_network", ip: "10.1.0.11"
    cont.vm.provider :virtualbox do |vm|
      vm.memory = 4096
    end
  end

  config.vm.define "network" do |net|
    net.vm.box = "ubuntu/trusty64"
    net.vm.hostname = "network"
    net.vm.network "private_network", ip: "10.1.0.21"
    net.vm.network "private_network", ip: "10.1.1.21", virtualbox__intnet: "tunnel"
    net.vm.provider :virtualbox do |vm|
      vm.memory = 2048
    end
  end

  config.vm.define "compute1" do |com1|
    com1.vm.box = "ubuntu/trusty64"
    com1.vm.hostname = "compute1"
    com1.vm.network "private_network", ip: "10.1.0.31"
    com1.vm.network "private_network", ip: "10.1.1.31", virtualbox__intnet: "tunnel"
  end

#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "site.yml"
#    ansible.inventory_path = "dev"
#    ansible.sudo = true
#end

end
