---

- name: install nova packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - nova-compute

- name: edit nova conf file
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: edit nova-compute. conf file
  template: src=nova-compute.conf.j2 dest=/etc/nova/nova-compute.conf

- name: Restart the Compute service services
  service: name=nova-compute state=restarted

- name: remove the SQLite database file
  file: path=/var/lib/nova/nova.sqlite state=absent

- name: chmod /var/lib/nova/instances for live migration
  file: path=/var/lib/nova/instances mode="o+x"

- name: edit /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ api_host }}:/instances /var/lib/nova/instances nfs4 defaults 0 0"

- name: mount nfs directory
  mount: name=/var/lib/nova/instances src={{ api_host }}:/instances fstype=nfs4 state=present

- name: edit libvirtd.conf
  copy: src=libvirtd.conf dest=/etc/libvirt/libvirtd.conf

- name: edit libvirt-bin
  replace: dest=/etc/default/libvirt-bin regexp='libvirtd_opts="-d"' replace='libvirtd_opts="-d -l"'

- name: restart libvirt-bin
  service: name=libvirt-bin state=restarted

#
# Add a networking component
#

- name: install neutron packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - neutron-{{ mechanism_driver }}-agent

- name: edit neutron conf file
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: Configure L2 agent
  template: src={{ mechanism_driver }}_agent.ini.j2 dest=/etc/neutron/plugins/ml2/{{ mechanism_driver }}_agent.ini

- name: Restart L2 agent
  service: name=neutron-{{ mechanism_driver }}-agent state=restarted
