---

- name: install nova packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - nova-compute
    - sysfsutils

- name: edit nova conf file
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: edit nova-compute. conf file
  template: src=nova-compute.conf.j2 dest=/etc/nova/nova-compute.conf

- name: Restart the Compute service services
  service: name=nova-compute state=restarted

- name: remove the SQLite database file
  file: path=/var/lib/nova/nova.sqlite state=absent

#
# Add a networking component
#

- name: install neutron packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - neutron-plugin-{{ mechanism_driver }}-agent

- name: edit neutron conf file
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: Configure L2 agent
  template: src={{ mechanism_driver }}_agent.ini.j2 dest=/etc/neutron/plugins/ml2/{{ mechanism_driver }}_agent.ini

- name: Restart L2 agent
  service: name=neutron-plugin-{{ mechanism_driver }}-agent state=restarted
